name: Build and Deploy RODE FE
on:
  push:
    branches:
      - main
      - dev-cicd-sonarqube
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: rode-battle-fe
  DOCKER_TAG: latest

jobs:
  fe-build:
    runs-on: [self-hosted, Linux, X64, fcode-japao-runner]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to F-Code Registry
        run: |
          echo "${{ secrets.F_CODE_DOCKER_PASS }}" | docker login ${{ secrets.F_CODE_DOCKER_REGISTRY_URL}} -u ${{ secrets.F_CODE_DOCKER_USER }} --password-stdin
          docker info

      - name: Build and push the image to F-Code Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.F_CODE_DOCKER_REGISTRY_URL}}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_TAG }}

      - name: List Docker images
        run: docker images

  staging-deploy:
    name: Deploy FE to F-Code Server
    runs-on: fcode-japao-runner
    needs: fe-build
    env:
      DOCKER_HUB_URL: ${{ secrets.F_CODE_DOCKER_REGISTRY_URL }}
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3

      - name: Log in to F-Code Registry
        run: |
          echo ${{ secrets.F_CODE_DOCKER_PASS }} | docker login ${{ secrets.F_CODE_DOCKER_REGISTRY_URL}} -u ${{ secrets.F_CODE_DOCKER_USER }} --password-stdin
          docker info

      - name: Clean Container, Image And Prepare For Deploy
        run: docker compose -f docker-compose.yaml -p rode-battle-fe down --rmi all -v

      - name: Deploy FE
        run: docker compose -f docker-compose.yaml -p rode-battle-fe up -d
